[package]
name = "susi-tools"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
susi-core = { workspace = true }
susi-sandbox-client = { workspace = true }
susi-config = { workspace = true }
susi-error = { workspace = true }
susi-paths = { workspace = true }
susi-native-client = { workspace = true }
susi-http-transport = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
dashmap = { workspace = true }

susi-vendor-mcp = { workspace = true }

[lints]
workspace = true

