[package]
name = "susi-tools"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
dashmap = { workspace = true }
parking_lot = { workspace = true }
libc = "0.2"
susi-error = { workspace = true }
susi-paths = { path = "../susi-paths" }
susi-sandbox = { workspace = true }
susi-native = { workspace = true }
