{{- if and .Values.secrets.inline (not .Values.secrets.existing) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "susi.fullname" . }}-keys
  labels:
    {{- include "susi.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets.inline }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
