[package]
name = "susi-config"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
susi-error = { workspace = true }
susi-paths = { workspace = true }
serde = { package = "susi-vendor-serde", path = "../susi-vendor-serde" }
serde_json = { package = "susi-vendor-serde-json", path = "../susi-vendor-serde-json" }
parking_lot = { package = "susi-vendor-parking-lot", path = "../susi-vendor-parking-lot" }
hex = { package = "susi-vendor-hex", path = "../susi-vendor-hex" }
sha2 = { package = "susi-vendor-sha2", path = "../susi-vendor-sha2" }
getrandom = { package = "susi-vendor-getrandom", path = "../susi-vendor-getrandom" }
ed25519-dalek = { package = "susi-vendor-ed25519-dalek", path = "../susi-vendor-ed25519-dalek" }
x25519-dalek = { package = "susi-vendor-x25519-dalek", path = "../susi-vendor-x25519-dalek" }
chacha20poly1305 = { package = "susi-vendor-chacha20poly1305", path = "../susi-vendor-chacha20poly1305" }

[lints]
workspace = true
