[package]
name = "susi-sandbox"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
bollard = "0.21.1"
futures = "0.3"
tracing = { workspace = true }
susi-error = { workspace = true }
susi-paths = { path = "../susi-paths" }
susi-config = { workspace = true }
hex = { workspace = true }
sha2 = { workspace = true }
getrandom = { workspace = true }

[lints]
workspace = true
