[package]
name = "susi-daemon"
version = "0.10.0"
license = "Apache-2.0"
edition = "2024"

[dependencies]
libc = "0.2"
serde_json = { workspace = true }
susi-core = { workspace = true }
susi-error = { path = "../susi-error" }
susi-gawd = { path = "../susi-gawd" }
susi-gmcp = { path = "../susi-gmcp" }
susi-sandbox = { path = "../susi-sandbox" }
susi-config = { workspace = true }
susi-gemi = { path = "../susi-gemi" }
susi-paths = { path = "../susi-paths" }
susi-server = { path = "../susi-server" }
susi-tools = { path = "../susi-tools" }
susi-agents = { path = "../susi-agents" }
tokio = { version = "1.53", features = ["full"] }
tracing = "0.1"
signal-hook = "0.4.4"

[features]
default = []
cuda = ["susi-gemi/cuda"]

[target."cfg(windows)".dependencies]
winapi = { version = "0.3", features = ["fileapi", "minwinbase"] }
