//! HTTP Gateway for Agent Invocation (Swarm OS Bullet 44)
//!
//! Exposes a RESTful gateway so traditional HTTP clients can invoke a specific
//! agent cell and await its JSON response.

use std::collections::HashMap;
use std::sync::RwLock;

/// Represents an incoming HTTP Request routed to an agent.
#[derive(Debug, Clone)]
pub struct AgentHttpRequest {
    pub cell_id: String,
    pub payload: Vec<u8>,
}

/// Represents the response generated by the agent.
#[derive(Debug, Clone)]
pub struct AgentHttpResponse {
    pub status_code: u16,
    pub payload: Vec<u8>,
}

/// HTTP router that forwards requests to exposed sandbox cells through an
/// injected engine executor.
pub struct HttpGateway {
    /// Maps cell IDs to a boolean indicating if they are exposed to the web.
    exposed_cells: RwLock<HashMap<String, bool>>,
}

impl Default for HttpGateway {
    fn default() -> Self {
        Self::new()
    }
}

impl HttpGateway {
    pub fn new() -> Self {
        Self {
            exposed_cells: RwLock::new(HashMap::new()),
        }
    }

    /// Exposes a cell to external HTTP traffic.
    pub fn expose_cell(&self, cell_id: &str) {
        let mut map = self
            .exposed_cells
            .write()
            .unwrap_or_else(|e| e.into_inner());
        map.insert(cell_id.to_string(), true);
    }

    /// Route an HTTP POST to its cell: 404 for unexposed cells, otherwise the
    /// executor's result as 200 or its error as 500.
    pub fn route_request<F>(
        &self,
        request: AgentHttpRequest,
        mut engine_executor: F,
    ) -> Result<AgentHttpResponse, String>
    where
        F: FnMut(&[u8]) -> Result<Vec<u8>, String>,
    {
        let map = self.exposed_cells.read().unwrap_or_else(|e| e.into_inner());

        if !map.contains_key(&request.cell_id) {
            return Err(format!(
                "HTTP 404: Cell '{}' is not exposed or does not exist",
                request.cell_id
            ));
        }

        // Execute via the engine
        match engine_executor(&request.payload) {
            Ok(result) => Ok(AgentHttpResponse {
                status_code: 200,
                payload: result,
            }),
            Err(e) => Ok(AgentHttpResponse {
                status_code: 500,
                payload: e.into_bytes(),
            }),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_http_gateway_routing() {
        let gateway = HttpGateway::new();

        gateway.expose_cell("agent-api");

        // Unexposed cell
        let res1 = gateway.route_request(
            AgentHttpRequest {
                cell_id: "agent-internal".to_string(),
                payload: b"{}".to_vec(),
            },
            |_| Ok(b"success".to_vec()),
        );
        assert!(res1.is_err());

        // Exposed cell
        let res2 = gateway.route_request(
            AgentHttpRequest {
                cell_id: "agent-api".to_string(),
                payload: b"{}".to_vec(),
            },
            |_| Ok(b"success".to_vec()),
        );
        assert!(res2.is_ok());
        assert_eq!(res2.unwrap().status_code, 200);

        // Exposed cell with error
        let res3 = gateway.route_request(
            AgentHttpRequest {
                cell_id: "agent-api".to_string(),
                payload: b"{}".to_vec(),
            },
            |_| Err("crash".to_string()),
        );
        let ok_res = res3.unwrap();
        assert_eq!(ok_res.status_code, 500);
        assert_eq!(ok_res.payload, b"crash");
    }
}
