//! Prometheus-compatible Metrics Aggregation (Swarm OS Bullet 76)
//!
//! Exposes a `/metrics` endpoint compatible with Prometheus for tracking
//! swarm health, tokens/sec, context lengths, and syscall ratios.

use std::sync::atomic::{AtomicU64, Ordering};
use std::collections::HashMap;
use std::sync::RwLock;

/// Aggregates metrics for the entire Swarm OS daemon.
pub struct MetricsManager {
    tokens_generated: AtomicU64,
    context_allocated_bytes: AtomicU64,
    syscalls_total: RwLock<HashMap<String, u64>>,
}

impl Default for MetricsManager {
    fn default() -> Self {
        Self::new()
    }
}

impl MetricsManager {
    pub fn new() -> Self {
        Self {
            tokens_generated: AtomicU64::new(0),
            context_allocated_bytes: AtomicU64::new(0),
            syscalls_total: RwLock::new(HashMap::new()),
        }
    }

    /// Records the generation of tokens.
    pub fn record_tokens(&self, count: u64) {
        self.tokens_generated.fetch_add(count, Ordering::Relaxed);
    }

    /// Records KV cache / context allocation size.
    pub fn record_context_allocation(&self, bytes: u64) {
        self.context_allocated_bytes.fetch_add(bytes, Ordering::Relaxed);
    }

    /// Records a syscall invocation.
    pub fn record_syscall(&self, op_name: &str) {
        let mut map = self.syscalls_total.write().unwrap_or_else(|e| e.into_inner());
        *map.entry(op_name.to_string()).or_insert(0) += 1;
    }

    /// Exports all metrics in Prometheus text exposition format.
    pub fn export_prometheus(&self) -> String {
        let mut out = String::new();

        // Tokens
        out.push_str("# HELP susi_tokens_generated_total Total LLM tokens generated by the swarm.\n");
        out.push_str("# TYPE susi_tokens_generated_total counter\n");
        out.push_str(&format!("susi_tokens_generated_total {}\n\n", self.tokens_generated.load(Ordering::Relaxed)));

        // Context Allocations
        out.push_str("# HELP susi_context_allocated_bytes Total bytes allocated for attention context.\n");
        out.push_str("# TYPE susi_context_allocated_bytes gauge\n");
        out.push_str(&format!("susi_context_allocated_bytes {}\n\n", self.context_allocated_bytes.load(Ordering::Relaxed)));

        // Syscalls
        out.push_str("# HELP susi_syscalls_total Total syscalls executed by the swarm OS.\n");
        out.push_str("# TYPE susi_syscalls_total counter\n");
        
        let map = self.syscalls_total.read().unwrap_or_else(|e| e.into_inner());
        for (op, count) in map.iter() {
            out.push_str(&format!("susi_syscalls_total{{op=\"{}\"}} {}\n", op, count));
        }
        
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_prometheus_export() {
        let metrics = MetricsManager::new();
        
        metrics.record_tokens(150);
        metrics.record_context_allocation(4096);
        metrics.record_syscall("infer");
        metrics.record_syscall("infer");
        metrics.record_syscall("tool_call");

        let export = metrics.export_prometheus();
        
        assert!(export.contains("susi_tokens_generated_total 150"));
        assert!(export.contains("susi_context_allocated_bytes 4096"));
        assert!(export.contains("susi_syscalls_total{op=\"infer\"} 2"));
        assert!(export.contains("susi_syscalls_total{op=\"tool_call\"} 1"));
    }
}
