//! Time-Travel Debugger & Message Replay (Swarm OS Bullet 95)
//!
//! Provides deterministic replay of a cell's message history to recreate an exact state.
//! Used for step-through debugging of AI agent interactions.

use std::collections::HashMap;
use std::sync::RwLock;

/// Represents a historical event received or generated by a cell.
#[derive(Debug, Clone)]
pub struct ReplayEvent {
    pub timestamp: u64,
    pub source_cell_id: String,
    pub payload: Vec<u8>,
}

/// A session for replaying events to recreate state.
pub struct ReplaySession {
    cell_id: String,
    events: Vec<ReplayEvent>,
    cursor: usize,
}

impl ReplaySession {
    /// Steps forward by one event.
    pub fn step_forward(&mut self) -> Option<&ReplayEvent> {
        if self.cursor < self.events.len() {
            let ev = &self.events[self.cursor];
            self.cursor += 1;
            Some(ev)
        } else {
            None
        }
    }

    /// Rewinds the cursor back to the beginning.
    pub fn reset(&mut self) {
        self.cursor = 0;
    }

    /// Returns the cell ID this session belongs to.
    pub fn cell_id(&self) -> &str {
        &self.cell_id
    }
}

/// Stores global event history for cells to enable time-travel debugging.
pub struct ReplayManager {
    history: RwLock<HashMap<String, Vec<ReplayEvent>>>,
}

impl Default for ReplayManager {
    fn default() -> Self {
        Self::new()
    }
}

impl ReplayManager {
    pub fn new() -> Self {
        Self {
            history: RwLock::new(HashMap::new()),
        }
    }

    /// Records a new event in a cell's history.
    pub fn record_event(&self, target_cell_id: &str, event: ReplayEvent) {
        let mut map = self.history.write().unwrap_or_else(|e| e.into_inner());
        map.entry(target_cell_id.to_string())
            .or_default()
            .push(event);
    }

    /// Starts a time-travel replay session for a given cell.
    pub fn start_session(&self, cell_id: &str) -> Option<ReplaySession> {
        let map = self.history.read().unwrap_or_else(|e| e.into_inner());
        map.get(cell_id).map(|events| ReplaySession {
            cell_id: cell_id.to_string(),
            events: events.clone(),
            cursor: 0,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_time_travel_replay() {
        let manager = ReplayManager::new();

        manager.record_event(
            "agent-1",
            ReplayEvent {
                timestamp: 1,
                source_cell_id: "user".to_string(),
                payload: b"Hello".to_vec(),
            },
        );

        manager.record_event(
            "agent-1",
            ReplayEvent {
                timestamp: 2,
                source_cell_id: "system".to_string(),
                payload: b"Context".to_vec(),
            },
        );

        let mut session = manager.start_session("agent-1").unwrap();

        // Step 1
        let ev1 = session.step_forward().unwrap();
        assert_eq!(ev1.payload, b"Hello");

        // Step 2
        let ev2 = session.step_forward().unwrap();
        assert_eq!(ev2.payload, b"Context");

        // EOF
        assert!(session.step_forward().is_none());

        // Time travel rewind
        session.reset();
        let ev1_again = session.step_forward().unwrap();
        assert_eq!(ev1_again.payload, b"Hello");
    }
}
