[package]
name = "susi"
version = "0.1.2023014"
edition = "2021"
authors = ["IntelliBitz", "Muthu Ramadoss", "SUSI EAI Core"]
description = "SUSI Intelligence Substrate Lightweight Native CLI Binary Launcher"
license = "Apache-2.0"
repository = "https://github.com/intellibitz/susi"
homepage = "https://github.com/intellibitz/susi"

[dependencies]

[profile.release]
opt-level = "z"     # Optimize for size
lto = true          # Link-time optimization
codegen-units = 1   # Single codegen unit for max optimization
panic = "abort"     # Remove panic unwinding code
strip = true        # Automatically strip symbols
