[package]
name = "susi-dsh-cell"
version = "0.14.1"
edition = "2021"

[dependencies]
susi-abi = { workspace = true, features = ["cell-server"] }
tokio = { package = "susi-vendor-tokio", path = "../susi-vendor-tokio" }
serde_json = { package = "susi-vendor-serde-json", path = "../susi-vendor-serde-json" }

[lints]
workspace = true
