[package]
name = "susi-core"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
dashmap = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
crossbeam = "0.8"
flume = { workspace = true }
parking_lot = { workspace = true }
regex = "1.11"
tracing = { workspace = true }
susi-error = { workspace = true }
