[package]
name = "susi-server"
version = "0.10.0"
license = "Apache-2.0"
edition = "2024"

[dependencies]
susi-core = { path = "../susi-core" }
susi-sandbox = { path = "../susi-sandbox" }
susi-error = { workspace = true }
susi-paths = { path = "../susi-paths" }

hyper = { version = "1.0", features = ["full"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
serde_json = "1.0"
tokio = { version = "1.53", features = ["full"] }
tokio-stream = "0.1"
rayon = "1.12"
bytes = "1.12"
tracing = "0.1"

[features]
default = []
cuda = []
